// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var React$1 = require("@storybook/react");
var Row$KalseljsCommunityPage = require("../../src/components/uikit/atomic/Row.bs.js");
var Constants$KalseljsCommunityPage = require("../../src/commons/Constants.bs.js");

function str(prim) {
  return prim;
}

var jsModule = module;

React$1.storiesOf(Constants$KalseljsCommunityPage.Storybook.storiesOf(/* `Components */[
            -791693002,
            /* Atomics */573549320
          ]), jsModule).add("Row", (function (param) {
        return React.createElement(Row$KalseljsCommunityPage.make, {
                    children: "Hi i am on row"
                  });
      }));

var StorybookConst = 0;

var Action = 0;

exports.StorybookConst = StorybookConst;
exports.Action = Action;
exports.str = str;
exports.jsModule = jsModule;
/* jsModule Not a pure module */
