// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var React$1 = require("@storybook/react");
var View$KalseljsCommunityPage = require("../../src/components/uikit/atomic/View.bs.js");
var Constants$KalseljsCommunityPage = require("../../src/commons/Constants.bs.js");

function str(prim) {
  return prim;
}

var jsModule = module;

React$1.storiesOf(Constants$KalseljsCommunityPage.Storybook.storiesOf(/* `Components */[
            -791693002,
            /* Atomics */573549320
          ]), jsModule).add("View", (function (param) {
        return React.createElement(View$KalseljsCommunityPage.make, {
                    children: "Hi i am on view"
                  });
      }));

var StorybookConst = 0;

var Action = 0;

exports.StorybookConst = StorybookConst;
exports.Action = Action;
exports.str = str;
exports.jsModule = jsModule;
/* jsModule Not a pure module */
