// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var View$KalseljsCommunityPage = require("../atomic/View.bs.js");
var Utils$KalseljsCommunityPage = require("../../../commons/Utils.bs.js");

var container = Css.style(/* :: */[
      Css.width(/* `percent */[
            -119887163,
            100
          ]),
      /* :: */[
        Css.height(/* `percent */[
              -119887163,
              100
            ]),
        /* :: */[
          Css.margin(Css.zero),
          /* :: */[
            Css.padding(Css.zero),
            /* :: */[
              Css.overflow(/* hidden */-862584982),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var Styles = {
  container: container
};

function Global(Props) {
  var children = Props.children;
  Utils$KalseljsCommunityPage.Styles.preset(/* () */0);
  return React.createElement(View$KalseljsCommunityPage.make, {
              style: container,
              children: children
            });
}

var make = Global;

var $$default = Global;

exports.Styles = Styles;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* container Not a pure module */
