// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReactHelmet = require("react-helmet");
var Utils$KalseljsCommunityPage = require("../../../commons/Utils.bs.js");

var description = "description";

var keywords = "keywords";

var keywordsDefaultValue = "community,javascript,javascript community,komunitas js kalimantan selatan,kalseljs";

var ogTitle = "og:title";

var ogDescription = "og:description";

var ogType = "og:type";

var ogTypeValue = "website";

var twitterCard = "twitter:card";

var twitterCardValue = "summary";

var Captions = {
  description: description,
  keywords: keywords,
  keywordsDefaultValue: keywordsDefaultValue,
  ogTitle: ogTitle,
  ogDescription: ogDescription,
  ogType: ogType,
  ogTypeValue: ogTypeValue,
  twitterCard: twitterCard,
  twitterCardValue: twitterCardValue
};

function SEO(Props) {
  var description$1 = Props.description;
  var lang = Props.lang;
  var title = Props.title;
  var keywords$1 = Props.keywords;
  var keywordsValue = Curry._2(Utils$KalseljsCommunityPage.$$Option.Infix.$pipe$question, keywords$1, keywordsDefaultValue);
  return React.createElement(ReactHelmet.Helmet, {
              htmlAttributes: lang,
              title: title,
              meta: /* array */[
                {
                  name: description,
                  content: description$1
                },
                {
                  name: keywords,
                  content: keywordsValue
                },
                {
                  property: ogTitle,
                  content: title
                },
                {
                  property: ogType,
                  content: ogTypeValue
                },
                {
                  property: ogDescription,
                  content: description$1
                },
                {
                  property: twitterCard,
                  content: twitterCardValue
                }
              ]
            });
}

var Helmet = 0;

var make = SEO;

var $$default = SEO;

exports.Helmet = Helmet;
exports.Captions = Captions;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
