// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function make(darkest, darker, neutral, lighter, lightest) {
  return /* record */[
          /* darkest : `hex */[
            5194459,
            darkest.substr(1)
          ],
          /* darker : `hex */[
            5194459,
            darker.substr(1)
          ],
          /* neutral : `hex */[
            5194459,
            neutral.substr(1)
          ],
          /* lighter : `hex */[
            5194459,
            lighter.substr(1)
          ],
          /* lightest : `hex */[
            5194459,
            lightest.substr(1)
          ]
        ];
}

var Spectrum = {
  make: make
};

var primary = make("#955B16", "#C67A1E", "#F89825", "#FCCC92", "#FEEAD3");

var secondary = make("#1C6D73", "#25919A", "#2EB5C0", "#97DAE0", "#EAF8F9");

var $$default = /* record */[
  /* primary */primary,
  /* secondary */secondary
];

exports.Spectrum = Spectrum;
exports.primary = primary;
exports.secondary = secondary;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* primary Not a pure module */
