// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function make(darkest, darker, neutral, lighter, lightest) {
  return /* record */[
          /* darkest : `hex */[
            5194459,
            darkest.substr(1)
          ],
          /* darker : `hex */[
            5194459,
            darker.substr(1)
          ],
          /* neutral : `hex */[
            5194459,
            neutral.substr(1)
          ],
          /* lighter : `hex */[
            5194459,
            lighter.substr(1)
          ],
          /* lightest : `hex */[
            5194459,
            lightest.substr(1)
          ]
        ];
}

var Spectrum = {
  make: make
};

var primary = make("#B73B36", "#DB5F4E", "#FF886C", "#FFAE90", "#FFC4A6");

var secondary = make("#B48173", "#D7B4A8", "#FBEDE6", "#FCF3EC", "#FDF6F1");

var black = make("#120D0E", "#161313", "#1A1A1A", "#313131", "#484848");

var $$default = /* record */[
  /* primary */primary,
  /* secondary */secondary,
  /* black */black
];

exports.Spectrum = Spectrum;
exports.primary = primary;
exports.secondary = secondary;
exports.black = black;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* primary Not a pure module */
