// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Utils$KalseljsCommunityPage = require("../../../commons/Utils.bs.js");

var base = Css.style(/* :: */[
      Css.fontFamily("Rubik, serif"),
      /* :: */[
        Css.fontWeight(/* medium */-20425611),
        /* :: */[
          Css.fontStyle(/* normal */812216871),
          /* :: */[
            Css.lineHeight(/* normal */812216871),
            /* :: */[
              Css.marginTop(/* `rem */[
                    5691738,
                    0
                  ]),
              /* :: */[
                Css.marginBottom(/* `rem */[
                      5691738,
                      0.8
                    ]),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

function createStyleBasedOnWeight(param) {
  if (param !== 861718677) {
    if (param >= 1046976787) {
      return Css.style(/* :: */[
                  Css.fontWeight(/* semiBold */-812709613),
                  /* [] */0
                ]);
    } else {
      return Css.style(/* :: */[
                  Css.fontWeight(/* bold */-1055161979),
                  /* [] */0
                ]);
    }
  } else {
    return Css.style(/* :: */[
                Css.fontWeight(/* medium */-20425611),
                /* [] */0
              ]);
  }
}

function createStyleBasedOnType(param) {
  if (param >= 16107) {
    if (param >= 16109) {
      if (param >= 16110) {
        return Css.style(/* :: */[
                    Css.fontSize(/* `rem */[
                          5691738,
                          1.1
                        ]),
                    /* :: */[
                      Css.lineHeight(/* `rem */[
                            5691738,
                            1.3
                          ]),
                      /* [] */0
                    ]
                  ]);
      } else {
        return Css.style(/* :: */[
                    Css.fontSize(/* `rem */[
                          5691738,
                          1.4
                        ]),
                    /* :: */[
                      Css.lineHeight(/* `rem */[
                            5691738,
                            1.95
                          ]),
                      /* [] */0
                    ]
                  ]);
      }
    } else if (param >= 16108) {
      return Css.style(/* :: */[
                  Css.fontSize(/* `rem */[
                        5691738,
                        1.8
                      ]),
                  /* :: */[
                    Css.lineHeight(/* `rem */[
                          5691738,
                          2.45
                        ]),
                    /* [] */0
                  ]
                ]);
    } else {
      return Css.style(/* :: */[
                  Css.fontSize(/* `rem */[
                        5691738,
                        2.25
                      ]),
                  /* [] */0
                ]);
    }
  } else if (param >= 16106) {
    return Css.style(/* :: */[
                Css.fontSize(/* `rem */[
                      5691738,
                      2.8
                    ]),
                /* :: */[
                  Css.lineHeight(/* `abs */[
                        4845682,
                        1.30
                      ]),
                  /* [] */0
                ]
              ]);
  } else {
    return Css.style(/* :: */[
                Css.fontSize(/* `rem */[
                      5691738,
                      3.4
                    ]),
                /* :: */[
                  Css.lineHeight(/* `abs */[
                        4845682,
                        1.25
                      ]),
                  /* [] */0
                ]
              ]);
  }
}

var Styles = {
  base: base,
  createStyleBasedOnWeight: createStyleBasedOnWeight,
  createStyleBasedOnType: createStyleBasedOnType
};

function Heading(Props) {
  var value = Props.value;
  var as_ = Props.as_;
  var match = Props.weight;
  var weight = match !== undefined ? match : /* Medium */861718677;
  var match$1 = Props.style;
  var style = match$1 !== undefined ? match$1 : "";
  var resolvedStyle = Css.merge(/* :: */[
        base,
        /* :: */[
          createStyleBasedOnWeight(weight),
          /* :: */[
            createStyleBasedOnType(as_),
            /* :: */[
              style,
              /* [] */0
            ]
          ]
        ]
      ]);
  var child = Curry._2(Utils$KalseljsCommunityPage.$$Option.Infix.$pipe$question, Curry._2(Utils$KalseljsCommunityPage.$$Option.Infix.$less$$great, value, (function (prim) {
              return prim;
            })), null);
  if (as_ >= 16107) {
    if (as_ >= 16109) {
      if (as_ >= 16110) {
        return React.createElement("h6", {
                    className: resolvedStyle
                  }, child);
      } else {
        return React.createElement("h5", {
                    className: resolvedStyle
                  }, child);
      }
    } else if (as_ >= 16108) {
      return React.createElement("h4", {
                  className: resolvedStyle
                }, child);
    } else {
      return React.createElement("h3", {
                  className: resolvedStyle
                }, child);
    }
  } else if (as_ >= 16106) {
    return React.createElement("h2", {
                className: resolvedStyle
              }, child);
  } else {
    return React.createElement("h1", {
                className: resolvedStyle
              }, child);
  }
}

var make = Heading;

exports.Styles = Styles;
exports.make = make;
/* base Not a pure module */
