// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Colors$KalseljsCommunityPage = require("./Colors.bs.js");

var context = React.createContext(Colors$KalseljsCommunityPage.$$default);

var make = context.Provider;

var Provider = {
  make: make
};

exports.context = context;
exports.Provider = Provider;
/* context Not a pure module */
