// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");

var jsMapperConstantArray = /* array */[/* tuple */[
    -313673905,
    "Typography"
  ]];

function tToJs(param) {
  return Js_mapperRt.binarySearch(1, param, jsMapperConstantArray);
}

function tFromJs(param) {
  return Js_mapperRt.revSearch(1, jsMapperConstantArray, param);
}

var Foundations = {
  tToJs: tToJs,
  tFromJs: tFromJs
};

var jsMapperConstantArray$1 = /* array */[/* tuple */[
    573549320,
    "Atomics"
  ]];

function tToJs$1(param) {
  return Js_mapperRt.binarySearch(1, param, jsMapperConstantArray$1);
}

function tFromJs$1(param) {
  return Js_mapperRt.revSearch(1, jsMapperConstantArray$1, param);
}

var Components = {
  tToJs: tToJs$1,
  tFromJs: tFromJs$1
};

function storiesOf(param) {
  if (param[0] >= 810877888) {
    return "Foundations | " + Js_mapperRt.binarySearch(1, param[1], jsMapperConstantArray);
  } else {
    return "Components | " + Js_mapperRt.binarySearch(1, param[1], jsMapperConstantArray$1);
  }
}

var Storybook = {
  Foundations: Foundations,
  Components: Components,
  storiesOf: storiesOf
};

exports.Storybook = Storybook;
/* No side effect */
