// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -85373939,
    "Molecules"
  ],
  /* tuple */[
    573549320,
    "Atomics"
  ],
  /* tuple */[
    810877888,
    "Foundations"
  ],
  /* tuple */[
    880159449,
    "Templates"
  ]
];

function tToJs(param) {
  return Js_mapperRt.binarySearch(4, param, jsMapperConstantArray);
}

function tFromJs(param) {
  return Js_mapperRt.revSearch(4, jsMapperConstantArray, param);
}

function toString(type_) {
  return Js_mapperRt.binarySearch(4, type_, jsMapperConstantArray);
}

var Storybook = {
  tToJs: tToJs,
  tFromJs: tFromJs,
  toString: toString
};

exports.Storybook = Storybook;
/* No side effect */
