// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Format = require("date-fns/format");

function formatDate(isoDateString) {
  return Format(new Date(isoDateString), "dddd, MMMM D, YYYY");
}

function $pipe$question(option, defaultValue) {
  if (option !== undefined) {
    return Caml_option.valFromOption(option);
  } else {
    return defaultValue;
  }
}

var Infix = {
  $pipe$question: $pipe$question,
  $great$great$eq: Belt_Option.flatMap,
  $less$$great: Belt_Option.map
};

var $$Option = {
  Infix: Infix
};

exports.formatDate = formatDate;
exports.$$Option = $$Option;
/* date-fns/format Not a pure module */
