// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var React$1 = require("@storybook/react");
var Heading$KalseljsCommunityPage = require("../../src/components/uikit/foundation/Heading.bs.js");
var Constants$KalseljsCommunityPage = require("../../src/commons/Constants.bs.js");

function str(prim) {
  return prim;
}

var jsModule = module;

React$1.storiesOf(Constants$KalseljsCommunityPage.Storybook.storiesOf(/* `Foundations */[
            810877888,
            /* Typography */-313673905
          ]), jsModule).add("Heading", (function (param) {
        return React.createElement(React.Fragment, undefined, React.createElement(Heading$KalseljsCommunityPage.make, {
                        value: "Javascript user group",
                        as_: /* H1 */16105
                      }), React.createElement(Heading$KalseljsCommunityPage.make, {
                        value: "Javascript user group",
                        as_: /* H2 */16106
                      }), React.createElement(Heading$KalseljsCommunityPage.make, {
                        value: "Javascript user group",
                        as_: /* H3 */16107
                      }), React.createElement(Heading$KalseljsCommunityPage.make, {
                        value: "Javascript user group",
                        as_: /* H4 */16108
                      }), React.createElement(Heading$KalseljsCommunityPage.make, {
                        value: "Javascript user group",
                        as_: /* H5 */16109
                      }), React.createElement(Heading$KalseljsCommunityPage.make, {
                        value: "Javascript user group",
                        as_: /* H6 */16110
                      }));
      }));

var StorybookConst = 0;

var Action = 0;

exports.StorybookConst = StorybookConst;
exports.Action = Action;
exports.str = str;
exports.jsModule = jsModule;
/* jsModule Not a pure module */
