// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var React$1 = require("@storybook/react");
var Text$KalseljsCommunityPage = require("../../src/components/uikit/foundation/Text.bs.js");
var Constants$KalseljsCommunityPage = require("../../src/commons/Constants.bs.js");

function str(prim) {
  return prim;
}

var jsModule = module;

React$1.storiesOf(Constants$KalseljsCommunityPage.Storybook.storiesOf(/* `Foundations */[
            810877888,
            /* Typography */-313673905
          ]), jsModule).add("Text", (function (param) {
        return React.createElement(React.Fragment, undefined, React.createElement(Text$KalseljsCommunityPage.make, {
                        children: "Normal Text"
                      }), React.createElement(Text$KalseljsCommunityPage.make, {
                        size: /* Large */48800667,
                        children: "Large Text"
                      }), React.createElement(Text$KalseljsCommunityPage.make, {
                        variant: /* Secondary */67972948,
                        children: "Secondary Text Color"
                      }));
      }));

var StorybookConst = 0;

var Action = 0;

exports.StorybookConst = StorybookConst;
exports.Action = Action;
exports.str = str;
exports.jsModule = jsModule;
/* jsModule Not a pure module */
