// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Theme$KalseljsCommunityPage = require("../uikit/foundation/Theme.js");
var Colors$KalseljsCommunityPage = require("../uikit/foundation/Colors.js");

function Store(Props) {
  var children = Props.children;
  return React.createElement(Theme$KalseljsCommunityPage.Provider.make, {
              value: Colors$KalseljsCommunityPage.$$default,
              children: children
            });
}

var make = Store;

var $$default = Store;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
