// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Theme$KalseljsCommunityPage = require("../uikit/foundation/Theme.bs.js");
var Colors$KalseljsCommunityPage = require("../uikit/foundation/Colors.bs.js");
var Locale$KalseljsCommunityPage = require("../../commons/Locale.bs.js");

function reducer(param, action) {
  return action[0];
}

function Store(Props) {
  var children = Props.children;
  return React.createElement(Locale$KalseljsCommunityPage.Provider.make, {
              children: React.createElement(Theme$KalseljsCommunityPage.Provider.make, {
                    value: Colors$KalseljsCommunityPage.$$default,
                    children: children
                  })
            });
}

var initialState = /* Bn */2;

var make = Store;

var $$default = Store;

exports.initialState = initialState;
exports.reducer = reducer;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
