// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Theme$ReactGatsbyTemplate = require("../uikit/foundation/Theme.bs.js");
var Colors$ReactGatsbyTemplate = require("../uikit/foundation/Colors.bs.js");

function Store(Props) {
  var children = Props.children;
  return React.createElement(Theme$ReactGatsbyTemplate.Provider.make, {
              value: Colors$ReactGatsbyTemplate.$$default,
              children: children
            });
}

var make = Store;

var $$default = Store;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
