// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Index$ReactTemplate = require("../../re/Index.js");

function MainPage(Props, _children) {
  return React.createElement(Index$ReactTemplate.make, { });
}

var make = MainPage;

var $$default = MainPage;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;