// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function MainPage(Props, _children) {
  return React.createElement("div", undefined, React.createElement("p", undefined, "KalselJS sss sssss xxx"));
}

var make = MainPage;

var $$default = MainPage;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
