// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function NotFound(Props) {
  return React.createElement("h1", undefined, "Not found");
}

NotFound.displayName = "404";

var make = NotFound;

var $$default = NotFound;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/*  Not a pure module */
