// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function NotFound(Props, _children) {
  return React.createElement("h1", undefined, "not found");
}

var make = NotFound;

var $$default = NotFound;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
