// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function str(prim) {
  return prim;
}

function Index(Props) {
  return React.createElement("div", undefined, React.createElement("p", undefined, "KalselJS"));
}

var make = Index;

var $$default = Index;

exports.str = str;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
